os: linux
dist: bionic
language: go
go:
 - 1.14
install:
 - echo 'deb http://archive.ubuntu.com/ubuntu/ focal universe' | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get -y install libolm3 libolm-dev
 - go get golang.org/x/lint/golint
 - go get github.com/fzipp/gocyclo

script: go build github.com/matrix-org/go-neb && ./hooks/pre-commit

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFhWmthbkFuV0VkeGNSSVFrV24lM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

